### ISSUE TITLE
Error inflating class error for lollipop version

### ISSUE THREAD

**Issue by sambasivapentyala** [iammert/StatusView#7]
Here's my customview class.

```
public class ConnectionStatusView extends StatusView {

    public ConnectionStatusView(Context context) {
        super(context, R.layout.sv_layout_complete, R.layout.sv_layout_error, R.layout.sv_layout_loading);
    }

    public ConnectionStatusView(Context context, AttributeSet attrs) {
        super(context, attrs, R.layout.sv_layout_complete, R.layout.sv_layout_error, R.layout.sv_layout_loading);
    }

    public ConnectionStatusView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr, R.layout.sv_layout_complete, R.layout.sv_layout_error, R.layout.sv_layout_loading);
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public ConnectionStatusView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes, R.layout.sv_layout_complete, R.layout.sv_layout_error, R.layout.sv_layout_loading);
    }
}
```

When I try to use this customview in Layout, the app is getting crashed. 

`10-23 20:24:19.614 4197-4197/com.dbydx.select E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.dbydx.select, PID: 4197
                                                                android.view.InflateException: Binary XML file line #139: Error inflating class com.dbydx.select.utils.ConnectionStatusView
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                    at com.dbydx.select.ui.home.main.chat.ChatFragment.onCreateView(ChatFragment.java:141)
                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                    at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                    at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1060)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                    at android.view.View.measure(View.java:16497)
                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
                                                                	at android.`

I'm not able find any solution on stackoverflow.

**Comment by sambasivapentyala** [comment]
Sorry, might be a wrong place to post
